% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  10pt,
  a4paper,oneside]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[left=0.5in,right=0.5in,top=0.5in,bottom=0.5in]{geometry}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{caption}
\usepackage{placeins}
\captionsetup{font=small}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Correlate Horizontal and Inclined CM21 signal INC \textasciitilde{} HOR.},
  pdfauthor={Natsis Athanasios; Alkiviadis Bais},
  colorlinks=true,
  linkcolor={Maroon},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}

\title{Correlate Horizontal and Inclined CM21 signal \textbf{INC \textasciitilde{} HOR}.}
\author{Natsis Athanasios\footnote{Laboratory of Atmospheric Physics, AUTH, \href{mailto:natsisphysicist@gmail.com}{\nolinkurl{natsisphysicist@gmail.com}}} \and Alkiviadis Bais\footnote{Laboratory of Atmospheric Physics, AUTH}}
\date{2023-03-15}

\begin{document}
\maketitle
\begin{abstract}
Compare Inclined CM21 with Global CM21 to produce a calibration factor for inclined, and new Global measurements to fill calibration period gaps in records.
\end{abstract}

{
\hypersetup{linkcolor=}
\setcounter{tocdepth}{2}
\tableofcontents
}
\hypertarget{description}{%
\section{Description}\label{description}}

\textbf{Source code: \href{https://github.com/thanasisn/CM_21_GLB/tree/main/CM21_inclined_global}{\texttt{github.com/thanasisn/CM\_21\_GLB/tree/main/CM21\_inclined\_global}}}

\begin{description}
\tightlist
\item[Got measurements from inclined CM-21:]
\(V_{IN}\)
\item[Use linear regression to get radiation:]
\(E_{IN} = β + α * V_{IN}\)
\end{description}

or

\begin{description}
\tightlist
\item[Use median of the ratio:]
\(E_{IN} = a * E_{GL}\)
\item[Assume:]
\(E_{IN} = E_{GL}\)
\item[Produce Global ``measurements'':]
\(V_{GL} = E_{IN} / S_{new}\)
\end{description}

Select an arbitrary \(S_{new}\) value for archive usage.

\hypertarget{data-overview}{%
\section{Data Overview}\label{data-overview}}

Investigate data of horizontal and inclined CM-21.

Inclined data are read from ``sirena'' directly.

Global data are produced by me.

Data view is extended to:

Start day: 2022-02-21

End day: 2022-06-27

Correlation period:

Start day exact: \textbf{2022-02-21 11:50:00} m:711

End day exact: \textbf{2022-06-27 08:40:00} m:521

Correlate data with sun elevation \textbf{\(>10^\circ\)}

\hypertarget{common-measurements}{%
\subsection{Common measurements}\label{common-measurements}}

Only simultaneous measurements for correlation.

\hypertarget{process}{%
\section{Process}\label{process}}

\hypertarget{compute-dark-signal-correction-for-inclined-cm-21.}{%
\subsection{Compute dark signal correction for inclined CM-21.}\label{compute-dark-signal-correction-for-inclined-cm-21.}}

We calculate zero offset as the \textbf{median} value of signal with:

\begin{itemize}
\tightlist
\item
  Data with Sun elevation angle \textbf{bellow \(-10^\circ\)}.
\item
  Data \textbf{span for dark signal 20} minutes for each ``morning'' and ``evening''.
\item
  We \textbf{interpolate dark signal} between the ``morning'' and ``evening'' offset for each day for the dark correction.
\end{itemize}

\newpage

\hypertarget{correlation-inclined-horizontal-cm-21.}{%
\subsection{Correlation Inclined \textasciitilde{} Horizontal CM-21.}\label{correlation-inclined-horizontal-cm-21.}}

\hypertarget{linear-regression}{%
\subsubsection{Linear regression}\label{linear-regression}}

Outliers selection by \textbf{\(2σ\) distance}.

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-12-1} \end{center}

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.2500}}
  >{\centering\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1528}}
  >{\centering\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1806}}
  >{\centering\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1389}}
  >{\centering\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\centering
~
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Estimate
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Std. Error
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
t value
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Pr(\textgreater\textbar t\textbar)
\end{minipage} \\
\midrule()
\endhead
\textbf{(Intercept)} & 0.007298 & 0.000424 & 17.21 & 6.159e-66 \\
\textbf{DT\$wattGLB} & 0.004643 & 7.29e-07 & 6369 & 0 \\
\bottomrule()
\end{longtable}

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 6\tabcolsep) * \real{0.2083}}
  >{\centering\arraybackslash}p{(\columnwidth - 6\tabcolsep) * \real{0.3056}}
  >{\centering\arraybackslash}p{(\columnwidth - 6\tabcolsep) * \real{0.1250}}
  >{\centering\arraybackslash}p{(\columnwidth - 6\tabcolsep) * \real{0.2361}}@{}}
\caption{Linear regression \textbf{RED}}\tabularnewline
\toprule()
\begin{minipage}[b]{\linewidth}\centering
Observations
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Residual Std. Error
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
\(R^2\)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Adjusted \(R^2\)
\end{minipage} \\
\midrule()
\endfirsthead
\toprule()
\begin{minipage}[b]{\linewidth}\centering
Observations
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Residual Std. Error
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
\(R^2\)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Adjusted \(R^2\)
\end{minipage} \\
\midrule()
\endhead
20599 & 0.03236 & 0.9995 & 0.9995 \\
\bottomrule()
\end{longtable}

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.1806}}
  >{\centering\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.0972}}@{}}
\caption{Outliers points}\tabularnewline
\toprule()
\begin{minipage}[b]{\linewidth}\centering
Var1
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Freq
\end{minipage} \\
\midrule()
\endfirsthead
\toprule()
\begin{minipage}[b]{\linewidth}\centering
Var1
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Freq
\end{minipage} \\
\midrule()
\endhead
2022-02-25 & 13 \\
2022-06-03 & 3 \\
2022-06-04 & 32 \\
2022-06-05 & 43 \\
2022-06-06 & 35 \\
2022-06-07 & 33 \\
2022-06-08 & 8 \\
2022-06-09 & 8 \\
2022-06-11 & 24 \\
2022-06-12 & 4 \\
2022-06-13 & 19 \\
2022-06-14 & 42 \\
2022-06-15 & 2 \\
2022-06-16 & 26 \\
2022-06-17 & 7 \\
2022-06-19 & 51 \\
2022-06-20 & 44 \\
2022-06-21 & 13 \\
2022-06-22 & 9 \\
2022-06-23 & 3 \\
2022-06-24 & 25 \\
2022-06-25 & 4 \\
2022-06-26 & 29 \\
2022-06-27 & 1 \\
\bottomrule()
\end{longtable}

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.2500}}
  >{\centering\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1528}}
  >{\centering\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1806}}
  >{\centering\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1389}}
  >{\centering\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\centering
~
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Estimate
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Std. Error
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
t value
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Pr(\textgreater\textbar t\textbar)
\end{minipage} \\
\midrule()
\endhead
\textbf{(Intercept)} & 0.007298 & 0.000424 & 17.21 & 6.159e-66 \\
\textbf{DT\$wattGLB} & 0.004643 & 7.29e-07 & 6369 & 0 \\
\bottomrule()
\end{longtable}

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 6\tabcolsep) * \real{0.2083}}
  >{\centering\arraybackslash}p{(\columnwidth - 6\tabcolsep) * \real{0.3056}}
  >{\centering\arraybackslash}p{(\columnwidth - 6\tabcolsep) * \real{0.1250}}
  >{\centering\arraybackslash}p{(\columnwidth - 6\tabcolsep) * \real{0.2361}}@{}}
\caption{Robust Linear regression \textbf{BLUE}}\tabularnewline
\toprule()
\begin{minipage}[b]{\linewidth}\centering
Observations
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Residual Std. Error
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
\(R^2\)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Adjusted \(R^2\)
\end{minipage} \\
\midrule()
\endfirsthead
\toprule()
\begin{minipage}[b]{\linewidth}\centering
Observations
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Residual Std. Error
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
\(R^2\)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Adjusted \(R^2\)
\end{minipage} \\
\midrule()
\endhead
20599 & 0.03236 & 0.9995 & 0.9995 \\
\bottomrule()
\end{longtable}

\newpage

\hypertarget{distribution-of-ratios}{%
\subsection{Distribution of ratios}\label{distribution-of-ratios}}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-13-1} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-13-2} \end{center}

\newpage

\hypertarget{floating-scale-daily-plot-after-dark-correction}{%
\subsection{Floating scale daily plot after dark correction}\label{floating-scale-daily-plot-after-dark-correction}}

Ratios are filtered for plotting

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-14-1} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-14-2} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-14-3} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-14-4} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-14-5} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-14-6} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-14-7} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-14-8} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-14-9} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-14-10} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-14-11} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-14-12} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-14-13} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-14-14} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-14-15} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-14-16} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-14-17} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-14-18} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-14-19} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-14-20} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-14-21} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-14-22} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-14-23} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-14-24} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-14-25} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-14-26} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-14-27} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-14-28} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-14-29} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-14-30} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-14-31} \end{center}

\newpage

\hypertarget{results}{%
\section{Results}\label{results}}

\hypertarget{generate-global-data-from-inclined.}{%
\subsection{Generate Global data from Inclined.}\label{generate-global-data-from-inclined.}}

Using the linear fit model

With removed outliers data points

\textbf{Radiometric values are on the same scale now}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-15-1} \end{center}

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.2500}}
  >{\centering\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1528}}
  >{\centering\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1806}}
  >{\centering\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1389}}
  >{\centering\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\centering
~
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Estimate
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Std. Error
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
t value
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Pr(\textgreater\textbar t\textbar)
\end{minipage} \\
\midrule()
\endhead
\textbf{(Intercept)} & 0.004347 & 0.0003017 & 14.41 & 7.709e-47 \\
\textbf{DT\$wattGLB} & 0.004652 & 5.274e-07 & 8820 & 0 \\
\bottomrule()
\end{longtable}

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 6\tabcolsep) * \real{0.2083}}
  >{\centering\arraybackslash}p{(\columnwidth - 6\tabcolsep) * \real{0.3056}}
  >{\centering\arraybackslash}p{(\columnwidth - 6\tabcolsep) * \real{0.1250}}
  >{\centering\arraybackslash}p{(\columnwidth - 6\tabcolsep) * \real{0.2361}}@{}}
\caption{Linear regression \textbf{RED}}\tabularnewline
\toprule()
\begin{minipage}[b]{\linewidth}\centering
Observations
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Residual Std. Error
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
\(R^2\)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Adjusted \(R^2\)
\end{minipage} \\
\midrule()
\endfirsthead
\toprule()
\begin{minipage}[b]{\linewidth}\centering
Observations
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Residual Std. Error
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
\(R^2\)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Adjusted \(R^2\)
\end{minipage} \\
\midrule()
\endhead
20121 & 0.02285 & 0.9997 & 0.9997 \\
\bottomrule()
\end{longtable}

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.2500}}
  >{\centering\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1528}}
  >{\centering\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1806}}
  >{\centering\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1389}}
  >{\centering\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1667}}@{}}
\toprule()
\begin{minipage}[b]{\linewidth}\centering
~
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Estimate
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Std. Error
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
t value
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Pr(\textgreater\textbar t\textbar)
\end{minipage} \\
\midrule()
\endhead
\textbf{(Intercept)} & 0.004347 & 0.0003017 & 14.41 & 7.709e-47 \\
\textbf{DT\$wattGLB} & 0.004652 & 5.274e-07 & 8820 & 0 \\
\bottomrule()
\end{longtable}

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 6\tabcolsep) * \real{0.2083}}
  >{\centering\arraybackslash}p{(\columnwidth - 6\tabcolsep) * \real{0.3056}}
  >{\centering\arraybackslash}p{(\columnwidth - 6\tabcolsep) * \real{0.1250}}
  >{\centering\arraybackslash}p{(\columnwidth - 6\tabcolsep) * \real{0.2361}}@{}}
\caption{Robust Linear regression \textbf{BLUE}}\tabularnewline
\toprule()
\begin{minipage}[b]{\linewidth}\centering
Observations
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Residual Std. Error
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
\(R^2\)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Adjusted \(R^2\)
\end{minipage} \\
\midrule()
\endfirsthead
\toprule()
\begin{minipage}[b]{\linewidth}\centering
Observations
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Residual Std. Error
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
\(R^2\)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Adjusted \(R^2\)
\end{minipage} \\
\midrule()
\endhead
20121 & 0.02285 & 0.9997 & 0.9997 \\
\bottomrule()
\end{longtable}

\newpage

\hypertarget{calibration-factor}{%
\subsection{Calibration factor}\label{calibration-factor}}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-16-1} \end{center}

\begin{longtable}[]{@{}
  >{\centering\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.1250}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.1667}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.1944}}@{}}
\caption{Calibration factors}\tabularnewline
\toprule()
\begin{minipage}[b]{\linewidth}\centering
~
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Parameter
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
CF
\end{minipage} \\
\midrule()
\endfirsthead
\toprule()
\begin{minipage}[b]{\linewidth}\centering
~
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Parameter
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
CF
\end{minipage} \\
\midrule()
\endhead
\textbf{4} & Simple\_lm & 0.004651566 \\
\textbf{3} & Robust\_lm & 0.004654711 \\
\textbf{1} & Median & 0.00466343 \\
\textbf{2} & Mean & 0.004761029 \\
\bottomrule()
\end{longtable}

\newpage

\hypertarget{plot-common-calibrated}{%
\subsection{Plot common calibrated}\label{plot-common-calibrated}}

\textbf{Using median as calibration factor}:

\textbf{0.004663430407}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-17-1} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-17-2} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-17-3} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-17-4} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-17-5} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-17-6} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-17-7} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-17-8} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-17-9} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-17-10} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-17-11} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-17-12} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-17-13} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-17-14} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-17-15} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-17-16} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-17-17} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-17-18} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-17-19} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-17-20} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-17-21} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-17-22} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-17-23} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-17-24} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-17-25} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-17-26} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-17-27} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-17-28} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-17-29} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-17-30} \end{center}

\begin{center}\includegraphics[width=1\linewidth]{CM21_incline_global_comparison_files/figure-latex/unnamed-chunk-17-31} \end{center}

\newpage

\hypertarget{sirena-archive-data-manipulation}{%
\section{Sirena archive data manipulation!!}\label{sirena-archive-data-manipulation}}

\[W = V \times 1 \frac {0.004663430407}\]

\[1 \frac 0.0046634 = gain \frac Sensitivity\]

\[gain = 4E-2\]

\[Sensitivity = 1.865e-04\]

\footnotesize

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.1806}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.3611}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 4\tabcolsep) * \real{0.4444}}@{}}
\caption{Affected sirena files.}\tabularnewline
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
day
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Original inclined CM-21
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Copied from inclined CM-21 to
horizontal
\end{minipage} \\
\midrule()
\endfirsthead
\toprule()
\begin{minipage}[b]{\linewidth}\raggedright
day
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Original inclined CM-21
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Copied from inclined CM-21 to
horizontal
\end{minipage} \\
\midrule()
\endhead
2022-02-28 & 28022201.LAP & 28022206.LAP \\
2022-03-01 & 01032201.LAP & 01032206.LAP \\
2022-03-02 & 02032201.LAP & 02032206.LAP \\
2022-03-03 & 03032201.LAP & 03032206.LAP \\
2022-03-04 & 04032201.LAP & 04032206.LAP \\
2022-03-05 & 05032201.LAP & 05032206.LAP \\
2022-03-06 & 06032201.LAP & 06032206.LAP \\
2022-03-07 & 07032201.LAP & 07032206.LAP \\
2022-03-08 & 08032201.LAP & 08032206.LAP \\
2022-03-09 & 09032201.LAP & 09032206.LAP \\
2022-03-10 & 10032201.LAP & 10032206.LAP \\
2022-03-11 & 11032201.LAP & 11032206.LAP \\
2022-03-12 & 12032201.LAP & 12032206.LAP \\
2022-03-13 & 13032201.LAP & 13032206.LAP \\
2022-03-14 & 14032201.LAP & 14032206.LAP \\
2022-03-15 & 15032201.LAP & 15032206.LAP \\
2022-03-16 & 16032201.LAP & 16032206.LAP \\
2022-03-17 & 17032201.LAP & 17032206.LAP \\
2022-03-18 & 18032201.LAP & 18032206.LAP \\
2022-03-19 & 19032201.LAP & 19032206.LAP \\
2022-03-20 & 20032201.LAP & 20032206.LAP \\
2022-03-21 & 21032201.LAP & 21032206.LAP \\
2022-03-23 & 23032201.LAP & 23032206.LAP \\
2022-03-24 & 24032201.LAP & 24032206.LAP \\
2022-03-25 & 25032201.LAP & 25032206.LAP \\
2022-03-26 & 26032201.LAP & 26032206.LAP \\
2022-03-27 & 27032201.LAP & 27032206.LAP \\
2022-03-28 & 28032201.LAP & 28032206.LAP \\
2022-03-29 & 29032201.LAP & 29032206.LAP \\
2022-03-30 & 30032201.LAP & 30032206.LAP \\
2022-03-31 & 31032201.LAP & 31032206.LAP \\
2022-04-01 & 01042201.LAP & 01042206.LAP \\
2022-04-02 & 02042201.LAP & 02042206.LAP \\
2022-04-03 & 03042201.LAP & 03042206.LAP \\
2022-04-04 & 04042201.LAP & 04042206.LAP \\
2022-04-05 & 05042201.LAP & 05042206.LAP \\
2022-04-06 & 06042201.LAP & 06042206.LAP \\
2022-04-07 & 07042201.LAP & 07042206.LAP \\
2022-04-08 & 08042201.LAP & 08042206.LAP \\
2022-04-09 & 09042201.LAP & 09042206.LAP \\
2022-04-10 & 10042201.LAP & 10042206.LAP \\
2022-04-11 & 11042201.LAP & 11042206.LAP \\
2022-04-12 & 12042201.LAP & 12042206.LAP \\
2022-04-13 & 13042201.LAP & 13042206.LAP \\
2022-04-14 & 14042201.LAP & 14042206.LAP \\
2022-04-15 & 15042201.LAP & 15042206.LAP \\
2022-04-16 & 16042201.LAP & 16042206.LAP \\
2022-04-17 & 17042201.LAP & 17042206.LAP \\
2022-04-18 & 18042201.LAP & 18042206.LAP \\
2022-04-19 & 19042201.LAP & 19042206.LAP \\
2022-04-20 & 20042201.LAP & 20042206.LAP \\
2022-04-21 & 21042201.LAP & 21042206.LAP \\
2022-04-22 & 22042201.LAP & 22042206.LAP \\
2022-04-23 & 23042201.LAP & 23042206.LAP \\
2022-04-24 & 24042201.LAP & 24042206.LAP \\
2022-04-25 & 25042201.LAP & 25042206.LAP \\
2022-04-26 & 26042201.LAP & 26042206.LAP \\
2022-04-27 & 27042201.LAP & 27042206.LAP \\
2022-04-28 & 28042201.LAP & 28042206.LAP \\
2022-04-29 & 29042201.LAP & 29042206.LAP \\
2022-04-30 & 30042201.LAP & 30042206.LAP \\
2022-05-01 & 01052201.LAP & 01052206.LAP \\
2022-05-02 & 02052201.LAP & 02052206.LAP \\
2022-05-03 & 03052201.LAP & 03052206.LAP \\
2022-05-04 & 04052201.LAP & 04052206.LAP \\
2022-05-05 & 05052201.LAP & 05052206.LAP \\
2022-05-06 & 06052201.LAP & 06052206.LAP \\
2022-05-07 & 07052201.LAP & 07052206.LAP \\
2022-05-08 & 08052201.LAP & 08052206.LAP \\
2022-05-09 & 09052201.LAP & 09052206.LAP \\
2022-05-10 & 10052201.LAP & 10052206.LAP \\
2022-05-11 & 11052201.LAP & 11052206.LAP \\
2022-05-12 & 12052201.LAP & 12052206.LAP \\
2022-05-13 & 13052201.LAP & 13052206.LAP \\
2022-05-14 & 14052201.LAP & 14052206.LAP \\
2022-05-15 & 15052201.LAP & 15052206.LAP \\
2022-05-16 & 16052201.LAP & 16052206.LAP \\
2022-05-17 & 17052201.LAP & 17052206.LAP \\
2022-05-18 & 18052201.LAP & 18052206.LAP \\
2022-05-19 & 19052201.LAP & 19052206.LAP \\
2022-05-20 & 20052201.LAP & 20052206.LAP \\
2022-05-21 & 21052201.LAP & 21052206.LAP \\
2022-05-22 & 22052201.LAP & 22052206.LAP \\
2022-05-23 & 23052201.LAP & 23052206.LAP \\
2022-05-24 & 24052201.LAP & 24052206.LAP \\
2022-05-25 & 25052201.LAP & 25052206.LAP \\
2022-05-26 & 26052201.LAP & 26052206.LAP \\
2022-05-27 & 27052201.LAP & 27052206.LAP \\
2022-05-28 & 28052201.LAP & 28052206.LAP \\
2022-05-29 & 29052201.LAP & 29052206.LAP \\
2022-05-30 & 30052201.LAP & 30052206.LAP \\
2022-05-31 & 31052201.LAP & 31052206.LAP \\
2022-06-01 & 01062201.LAP & 01062206.LAP \\
2022-06-02 & 02062201.LAP & 02062206.LAP \\
2022-06-03 & 03062201.LAP & 03062206.LAP \\
\bottomrule()
\end{longtable}

\normalsize

For the first file of the period:

2022-02-28, 28022201.LAP, 28022206.LAP

\begin{itemize}
\tightlist
\item
  Lines after 711 will be included to the horizontal.
\item
  Lines before 701 will be included to the inclined.
\end{itemize}

For the last file of the period:

2022-06-03, 03062201.LAP, 03062206.LAP

\begin{itemize}
\tightlist
\item
  Lines before 521 will be included to the horizontal.
\item
  Lines after 531 will be included to the inclined.
\end{itemize}

The intermediate lines will be set to ``NA'' (``-9'') for both instruments.

A backup of the whole year for each instrument have been created prior to edits.

\textbf{END}

\begin{verbatim}
2023-03-15 09:06:23.4 athan@tyler CM21_incline_global_comparison.R 1.000094 mins
\end{verbatim}

\end{document}
