---
title:    Instruments Journal
author:   Thanasis N
geometry: "a4paper,left=1cm,right=1cm,top=1cm,bottom=1cm"

header-includes: |
    \usepackage{fontspec}
    \usepackage{xunicode}
    \usepackage{xltxtra}
    \setmainfont[Scale=1.0]{Linux Libertine O}

#   \usepackage{xgreek}
---
